services:
  oracle:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-db
    environment:
      ORACLE_DATABASE: laros    # Cria o banco "laros"
      APP_USER: laros           # Cria o usuário "laros"
      APP_USER_PASSWORD: laros  # Define a senha do usuário "laros"
      ORACLE_PASSWORD: laros    # Senha do usuário SYSTEM
    healthcheck:
      test: [ "CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s system/oracle@localhost/XEPDB1 || exit 1" ]
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 60s
    ports:
      - "1521:1521"
    networks:
      - spring-net
    volumes:
      - oracle-data:/opt/oracle/oradata
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_volume:/root/.ollama
    networks:
      - spring-net
    environment:
      OLLAMA_LLM_LIBRARY: "cuda"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ "gpu" ]
              count: all
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laros-api
    depends_on:
      oracle:
        condition: service_healthy
    networks:
      - spring-net
    volumes:
      # Montando o código-fonte e o target para refletir alterações no container
      - ./src:/app/src
      - ./target:/app/target
      # Maven local cache
      - ~/.m2:/root/.m2
      # Monta o arquivo pom.xml
      - ./pom.xml:/app/pom.xml
    env_file: "./.env"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/LAROS
    ports:
      - "8080:8080"
    command: ["mvn", "spring-boot:run", "-Dspring-boot.run.fork=false"]

volumes:
  oracle-data:
  ollama_volume:

networks:
  spring-net:
    driver: bridge